@endpointAuth = http://localhost:3000/api/v1/auth
@endpointUsers = http://localhost:3000/api/v1/users

@endpointCart = http://localhost:3000/api/v1/cart

@idUser = 6941e11efc5e19b1e5df9e00
@productId = 68ffb3cfe8a92809d71723ff
# @name login

POST {{endpointAuth}} HTTP/1.1
content-type: application/json

{ 
    "email": "alex.ferguson@gmail.com",
    "password": "2password12345"
}


###
@accessToken = {{login.response.body.accessToken}}


###
### POST Request for a cart
POST {{endpointCart}}/{{productId}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "productId": "68ffb3cfe8a92809d71723ff"
}


###
### PUT Request for a cart
PUT {{endpointCart}} HTTP/1.1
content-type: application/json

{ 
  "userId": "69454e4dfb26cbed5ef6c6e1" ,
  "productId": "68ffb13529d434897dcb235f",
  "quantity": 3
}


###
### GET Request for a cart
GET {{endpointCart}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}


###
### DELETE Request for a cart
DELETE  {{endpointCart}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}
